[package]
name = "passwd-matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix-sdk = "0.6.2"
pwsafer = "0.1.3"

uuid = "1.6"
sha2 = "0.9.2"

[dependencies.clap]
version = "4"
features = ["derive"]

[patch.crates-io]
pwsafer = { path = "third-party/pwsafer" }
