[package]
name = "pwsafer"
version = "0.1.3"
edition = "2021"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>", "Gabriel Vukovic <gabriel.vukovic@student.tugraz.at>"]
description = "A library for reading and writing Password Safe databases."

# homepage = "https://github.com/"
# documentation = "https://docs.rs/pwsafer/"
readme = "README.md"
keywords = ["password"]
categories = ["cryptography"]
license = "Unlicense"
repository = "https://github.com/1uckyPh4nt0m/pwsafer"

[dependencies.cbc]
version = "0.1.2"
[dependencies.block-padding]
version = "0.3.2"

[dependencies.byteorder]
version = "1"

[dependencies.hmac]
version = "0.12.0"

[dependencies.rand]
version = "0.8.4"

[dependencies.secrets]
version = "1.2"

[dependencies.sha2]
version = "0.10.8"

[dependencies.twofish]
version = "0.7.1"
