[package]
name = "systemd-pwsafe-credentials"
description = "Provide data from a pwsafe file over a systemd credentials socket"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.41", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
uuid = { version = "1.10", features = ["serde"] }
pwsafer = { path = "../../third-party/pwsafer" }
uapi = "0.2.13"
